---
title: "11-Deseq2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
```

```{r}
library(DESeq2)

```


```{r}
data <- read.table("analyses/Abundance-merge.txt", header = T, sep = "\t")

rownames(data) <- data$target_id
data <- data[,-1]
head(data)
```







```{r}
head(data)
str(data)
```


```{r}
deseq2.colData <- data.frame(condition=factor(c(rep("un-infected", 4), rep("infected", 4))), 
                             type=factor(rep("single-read", 8)))
rownames(deseq2.colData) <- colnames(data)
deseq2.dds <- DESeqDataSetFromMatrix(countData = (data),
                                     colData = deseq2.colData, 
                                     design = ~ condition)
```

```{r}
deseq2.dds <- DESeq(deseq2.dds)
deseq2.dds
```




```{r}
deseq2.res <- results(deseq2.dds)

deseq2.res
```



```{r}
dim(deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ])

```


```{r}
summary(deseq2.res)
```


```{r}
sum(deseq2.res$padj < 0.1, na.rm=TRUE)

```


```{r}
res05 <- results(deseq2.dds, alpha=0.05)
summary(res05)
head(res05)
```


```{r}
sum(res05$padj < 0.05, na.rm=TRUE)

```

```{r}
plotMA(res05, ylim=c(-2,2))

```

```{r}
tmp <- deseq2.res
# The main plot
plot(tmp$baseMean, tmp$log2FoldChange, pch=20, cex=0.45, ylim=c(-3, 3), log="x", col="darkgray",
     main="Hematodinium Infection  (pval <= 0.005)",
     xlab="mean of normalized counts",
     ylab="Log2 Fold Change")
# Getting the significant points and plotting them again so they're a different color
tmp.sig <- deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.005, ]
points(tmp.sig$baseMean, tmp.sig$log2FoldChange, pch=20, cex=0.45, col="red")
# 2 FC lines
abline(h=c(-1,1), col="blue")

```

```{r}
tmp <- deseq2.res
# The main plot
plot(tmp$baseMean, tmp$log2FoldChange, pch=20, cex=0.45, ylim=c(-3, 3), log="x", col="darkgray",
     main="Hematodinium Infection  (pval <= 0.05)",
     xlab="mean of normalized counts",
     ylab="Log2 Fold Change")
# Getting the significant points and plotting them again so they're a different color
tmp.sig <- deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ]
points(tmp.sig$baseMean, tmp.sig$log2FoldChange, pch=20, cex=0.45, col="red")
# 2 FC lines
abline(h=c(-1,1), col="blue")

```



```{r}
write.table(tmp.sig, "analyses/Crab_DEGlist.txt", row.names = T, quote = FALSE, sep = "\t")

```

